# Generated by Django 4.0 on 2022-02-13 06:34

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('phone_wa', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('identity', models.CharField(max_length=50)),
                ('identity_no', models.CharField(max_length=20)),
                ('identity_img', models.ImageField(blank=True, null=b'I01\n', upload_to=base.models.filepath)),
                ('address_temp', models.TextField()),
                ('address', models.TextField()),
                ('seller_type', models.CharField(max_length=20)),
                ('remarks', models.TextField()),
            ],
        ),
    ]
